# Utiliser une image Python légère
FROM python:3.9-slim

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers nécessaires
COPY requirements.txt .
COPY streamlit_app.py /app/streamlit_app.py
COPY models /app/models
COPY data /app/data

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Exposer le port 8501 (port par défaut de Streamlit)
EXPOSE 8501

# Lancer l’application Streamlit
CMD ["streamlit", "run", "streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0"]
