# Utiliser une image Python légère
FROM python:3.9-slim

# Installer MLflow et ses dépendances
RUN pip install --no-cache-dir mlflow

# Définir le dossier de travail
WORKDIR /mlflow

# Exposer le port MLflow
EXPOSE 5000

# Lancer MLflow
CMD ["mlflow", "server", "--host", "0.0.0.0", "--port", "5000"]
